namespace FullEditorDemo;

internal static class Program
{
    [STAThread]
    static void Main()
    {
        // To activate your purchased license, set
        //   SpiceLogic.HtmlEditor.WinForms.WinFormHtmlEditor.LicenseKey = "YOUR-LICENSE-KEY-HERE";
        // here, before creating any editor instance. Without a key the editor runs a 14-day trial.

#if NET6_0_OR_GREATER
        // ApplicationConfiguration.Initialize() is source-generated by the SDK and only
        // available on .NET 6 and newer. On .NET Framework, set the same defaults the
        // classic way.
        ApplicationConfiguration.Initialize();
#else
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
#endif
        Application.Run(new MainForm());
    }
}
