namespace Quickstart;

internal static class Program
{
    [STAThread]
    static void Main()
    {
#if NET6_0_OR_GREATER
        // ApplicationConfiguration.Initialize() is source-generated by the SDK and only
        // available on .NET 6 and newer. On .NET Framework, set the same defaults the
        // classic way.
        ApplicationConfiguration.Initialize();
#else
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
#endif
        Application.Run(new MainForm());
    }
}
